services:
  schedy-nginx:
    image: localhost/schedy-nginx
    build:
      context: ../
      dockerfile: ./compose/nginx/Dockerfile
    container_name: schedy-nginx
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_completed_successfully

  database:
    image: localhost/schedy-postgres
    build:
      context: ../
      dockerfile: ./compose/postgres/Dockerfile
    container_name: schedy-pg
    ports:
      - "5432:5432"

  seapig-server:
    image: localhost/schedy-server-devel
    container_name: schedy-seapig-server
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    command: seapig-server --disable-json-diff
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_completed_successfully

  seapig-worker:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    environment:
      RAILS_ENV=production
    command: seapig-worker
    deploy:
      mode: replicated
      replicas: 12
    depends_on:
      database:
        condition: service_completed_successfully
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: a86416f38d79d6c8d8c58d030f9df72a418cb7574f3c6f5b15a7a0140fc0e41aee8a38a907fdacc59a57f3d03c028addd16d1e0b206aabae83c6d25a89177502

  schedy-router:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    container_name: schedy-router
    command: seapig-router-session-manager
    depends_on:
      database:
        condition: service_completed_successfully

  schedy-status-saver:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    container_name: schedy-status-saver
    command: ruby bin/worker-status-saver http://127.0.0.1:3001/seapig
    depends_on:
      database:
        condition: service_completed_successfully

  seapig-notifier:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    container_name: schedy-seapig-notifier
    command: seapig-postgresql-notifier
    depends_on:
      database:
        condition: service_completed_successfully

  schedy-dealer:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    container_name: schedy-dealer
    command: ruby bin/dealer http://127.0.0.1:3001/seapig http://127.0.0.1:3000/
    depends_on:
      database:
        condition: service_completed_successfully

  rails:
    image: localhost/schedy-server-devel
    build:
      context: ../
      dockerfile: ./compose/server/Dockerfile
    container_name: schedy-server-rails
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 34df6aa6edcd1868327cd44f94ea4d57f98683a2a1edc6669ddd8c1f15e9e44b0807ae6ab30a903798bcb67b19a04af643a6d43219be78b001024f12108aaf23
    command: rails server -p 3100
    ports:
      - "3100:3100"
    depends_on:
      database:
        condition: service_completed_successfully

  webssh:
    image: localhost/schedy-webssh-server
    build:
      context: ../
      dockerfile: ./compose/util/webssh.Dockerfile
    container_name: schedy-webssh-server
    command : /usr/local/bin/node index.js
    ports:
      - "2222:7777"
    depends_on:
      database:
        condition: service_completed_successfully
